# This workflow file is licensed under GNU GPL v2.0
name: Build OpenTTD for emscripten

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'OpenTTD ref'
        type: string
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:3.1.42
    steps:
    - uses: actions/checkout@v3
      with:
        repository: OpenTTD/OpenTTD
        ref: ${{ inputs.ref }}
    - name: Cache
      uses: actions/cache@v4
      with:
        path: /emsdk/upstream/emscripten/cache
        key: 3.1.42-${{ runner.os }}
    - name: Do patch
      run: |
        cd /emsdk/upstream/emscripten
        patch -p1 < ${GITHUB_WORKSPACE}/os/emscripten/emsdk-liblzma.patch
    - name: Build host tools
      run: |
        mkdir build-host
        cd build-host
        cmake .. -DOPTION_TOOLS_ONLY=ON
        make -j$(nproc) tools
    - name: Install GCC problem matcher
      uses: ammaraskar/gcc-problem-matcher@master
    - name: Build the game
      run: |
        mkdir build
        cd build
        cmake .. -DHOST_BINARY_DIR=../build-host -DCMAKE_BUILD_TYPE=Release -DOPTION_USE_ASSERTS=OFF
        make -j$(nproc)
    - name: Copy useful files
      run: |
        mkdir _site
        cp build/openttd.js build/openttd.html build/openttd.wasm build/openttd.data _site
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
